object Versions {
    const val APPCOMPAT = "1.4.2"
    const val MATERIAL = "1.6.1"
    const val CORE_KTX = "1.8.0"
    const val COROUTINES = "1.6.0"
    const val ROOM = "2.4.3"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.4.0"
    const val LIFECYCLE = "2.4.0"
    const val CONSTRAIN_LAYOUT = "2.1.4"
    const val DAGGER = "2.40.5"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.9.0"
    const val MOSHI = "1.11.0"
    const val DATABINDING = "3.1.4"

    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.1"
    const val ROBOELECTRIC = "4.4"
    const val MOCKK = "1.10.2"
    const val ASSERTJ = "3.17.2"
    const val COROUTINE_TEST = "1.6.0"
    const val MOCK_WEB_SERVER = "4.9.0"
    const val ESPRESSO = "3.3.0"
    const val FRAGMENT_TEST = "1.2.5"
}